In [1]:
import numpy as np

In [2]:
b = np.array([[1,2,3],[4,5,6]])

In [3]:
b.shape

(2, 3)

In [4]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
b.reshape((-1,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = np.array([1,2,3,4,5,6])
a.reshape(-1, 1)
b = [0,2,1,1,1,2,2,2]
c = a[b]
c

array([1, 3, 2, 2, 2, 3, 3, 3])

In [ ]:
import tens